### PR TITLE
Add 1.23 builds for Bottlerocket

### PR DESCRIPTION
**Pull request by mitalipaygude**
*Issue #, if available:*

*Description of changes:*
/hold till the bottlerocket 1.8.0 release is out.

1.8.0 was released => https://github.com/bottlerocket-os/bottlerocket/releases/tag/v1.8.0
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jaxesn** [comment]
There may need to be an update to the admin container. I think that is mentioned in the readme not sure

**Comment by mitalipaygude** [comment]
The job was failing because it couldn't find the 1.8.0 ovas, which is why I put a hold on it till it was released. Ready for merging now.

**Review by abhay-krishna — APPROVED** [review]
/lgtm

**Review by abhay-krishna — APPROVED** [review]
/lgtm

**Pull request merged**
