### PR TITLE
Update bottlerocket-bootstrap to go 1.20

### PR DESCRIPTION
**Pull request by g-gaston**
*Description of changes:*
Also update k8s.io/client-go to latest, v0.26.2. That takes care of updating all sensitive transient dependencies as well, like go text and go net.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jaxesn** [comment]
Would you mind add 1.20 to this as well

https://github.com/aws/eks-anywhere-build-tooling/blob/main/build/lib/install_go_versions.sh#L43

**Comment by g-gaston** [comment]
> Would you mind add 1.20 to this as well
> 
> https://github.com/aws/eks-anywhere-build-tooling/blob/main/build/lib/install_go_versions.sh#L43

done

**Review by TerryHowe — APPROVED** [review]
/lgtm

**Pull request merged**
