### PR TITLE
Fix emissary crd build

### PR DESCRIPTION
**Pull request by jonahjon**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by TerryHowe** [comment]
should probably use `git checkout main; git reset --hard upstream/main` and `get rebase upstream/main` more often

**Comment by jonahjon** [comment]
> 

yea I do this sometimes, but had been lazy recently I'll try to do that again.

**Pull request merged**
