### PR TITLE
Add build logic for gRPC health probe project

### PR DESCRIPTION
**Pull request by abhay-krishna**
Adding build logic for the [gRPC health probe](https://github.com/grpc-ecosystem/grpc-health-probe) project. This binary will be embedded into the PBNJ image.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by jaxesn — CHANGES_REQUESTED** [review]
Lets add a readme

**Comment by abhay-krishna** [comment]
> Lets add a readme

Ahh I knew I was missing something.

**Review by jaxesn — APPROVED** [review]
/lgtm

**Comment by TerryHowe** [comment]
will this fix the build?

**Pull request merged**
