### PR TITLE
Bump cluster-api, cert-manager and kind to latest versions.

### PR DESCRIPTION
**Pull request by abhay-krishna**
Bumping cluster-api to version `v1.4.4`. In this release, upstream CAPI upgraded to cert-manager `v1.12.2` and kind `v0.20.0`, so bumping those in step with the CAPI version bump.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by abhay-krishna** [comment]
Expected failure since the artifact is not available in S3 yet
/override eks-anywhere-cli-tools-tooling-presubmit

**Review by g-gaston — COMMENTED** [review]
/lgtm
/hold
are we confident with the tests results from v1.4.3?
unhold whenever you are ready

**Comment by abhay-krishna** [comment]
> /lgtm /hold are we confident with the tests results from v1.4.3? unhold whenever you are ready

I'm holding until the tests stabilize a bit. The non-packages tests are performing fine with CAPI v1.4.3

**Review by jaxesn — APPROVED** [review]

**Pull request merged**
