### PR TITLE
Adding tinkerbell/boots project to build tooling

### PR DESCRIPTION
**Pull request by pokearu**
*Description of changes:*
Adding project `tinkerbell/boots` to build tooling. We are currently checking in iPXE dependencies.
Will update the project after formulating a good way to build the dependencies.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by pokearu** [comment]
/hold
Holding for presubmits [PR](https://github.com/aws/eks-anywhere-prow-jobs/pull/78)

**Review by jaxesn — APPROVED** [review]
I keep going over this looking for something but I got nothing to say on this one! Amazing work!
Let me know if all the cdk and prow work is all done and I'll merge

**Comment by pokearu** [comment]
> I keep going over this looking for something but I got nothing to say on this one! Amazing work! Let me know if all the cdk and prow work is all done and I'll merge

Thank you 😄  Was holding the prow PR for the release, will get that merged soon.

**Review by jaxesn — APPROVED** [review]
/lgtm

**Pull request merged**
