### PR TITLE
Switches to al2023 for the kind image to fix cgroups v2

### PR DESCRIPTION
**Pull request by jaxesn**
*Issue #, if available:*

*Description of changes:*
 
We have never supported running eks-a bootstrap or docker based clusters on hosts configured to use cgroups v2. This is because our kind image is based on AL2 which ships with a version of systemd which does not support v2.

AL23 just recently went GA'd and does support cgroup v2. We have been building minimal images based on AL22 (now AL23) since last year. I have done some testing across various instances and OSs and kind images built off the new AL23 base appear to work just fine.

I plan to merge this after our 0.15 release in 2 weeks to avoid risking the release and to give us adequate bake time internally before including in either the 0.16 release or a future patch of 0.15.

ref:
https://github.com/aws/eks-anywhere/issues/838
https://github.com/aws/eks-anywhere/issues/941
https://github.com/aws/eks-anywhere/issues/792
https://github.com/aws/eks-anywhere/pull/1023

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by jonathanmeier5 — COMMENTED** [review]
Looks reasonable to me. Defer to others more knowledgeable, happy to lgtm if necessary.

**Review by g-gaston — APPROVED** [review]

**Pull request merged**
