### PR TITLE
Bump Flux version from v0.23 to v0.25

### PR DESCRIPTION
**Pull request by jiayiwang7**
*Issue #, if available:*

*Description of changes:*

- FluxV2: v0.23.0 -> v0.25.1
- Helm Controller: v0.13.0 -> v0.15.0
- Kustomization Controller: v0.18.0 -> v0.19.0
- Notification Controller: v0.18.1 -> v0.20.1
- Source Controller: v0.18.0 -> v0.20.1

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by g-gaston — APPROVED** [review]

**Review by abhay-krishna — APPROVED** [review]
/lgtm

**Pull request merged**
