### PR TITLE
Update Golang version for CAPX

### PR DESCRIPTION
**Pull request by thunderboltsid**
Update Makefile to set Go Version to 1.19

Generated checksums using `make update-attribution-checksums-docker`.

### CODE REVIEW

**Comment by thunderboltsid** [comment]
@abhinavmpandey08 Need an ok-to-test :)

**Comment by thunderboltsid** [comment]
Need an updated builder-base image in prowjob that has go1.19 https://github.com/aws/eks-anywhere-prow-jobs/pull/205

**Review by abhinavmpandey08 — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
