### PR TITLE
Backport ami build fixes

### PR DESCRIPTION
**Pull request by abhay-krishna**
Backporting #2350 and #2352 to release-0.17.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by jaxesn — APPROVED** [review]

**Comment by abhay-krishna** [comment]
/override cluster-api-provider-cloudstack-tooling-presubmit etcdadm-controller-tooling-presubmit etcdadm-controller-tooling-presubmit

**Comment by abhay-krishna** [comment]
/override imagebuilder-1-23-presubmit imagebuilder-1-24-presubmit  imagebuilder-1-25-presubmit  imagebuilder-1-26-presubmit  imagebuilder-1-27-presubmit

**Pull request merged**
