### PR TITLE
Bumping CAPC to v0.4.3

### PR DESCRIPTION
**Pull request by maxdrib**
*Issue #, if available:*

*Description of changes:*
This change will enable us to build the latest CAPC changes to support the upcoming EKS-A release

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by vignesh-goutham — APPROVED** [review]

**Comment by abhay-krishna** [comment]
We also need changes on the EKS-A release tooling side [like this](https://github.com/aws/eks-anywhere/pull/2052/files) to promote CAPC assets/bundle out of the dev-release check, and into the production bundle generation logic.

**Pull request merged**
