### PR TITLE
Raw Image Builds on CI

### PR DESCRIPTION
**Pull request by vignesh-goutham**
*Description of changes:*
Changing raw builds on CI to use image builder cli.

Fixes: #1136 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by abhay-krishna** [comment]
Are we skipping rhel for this change?

**Comment by vignesh-goutham** [comment]
> Are we skipping rhel for this change?

Yea, I will add them back after cutting release branch.

**Pull request merged**
