### PR TITLE
Fix dependencies being empty if undefined

### PR DESCRIPTION
**Pull request by lewisdiamond**
*Description of changes:*
Fix dependencies being generated with empty list when none are defined.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jaxesn** [comment]
does this need cherrypicked?

**Comment by jaxesn** [comment]
if emissary fails due to space issue, just override it

**Comment by lewisdiamond** [comment]
@jaxesn I don't think this needs to be cherrypicked, it's just for packages.

**Comment by lewisdiamond** [comment]
/cherry-pick release-0.12
Just to limit the diff

**Pull request merged**
