### PR TITLE
Bumping capc to latest version which fixes some bugs

### PR DESCRIPTION
**Pull request by maxdrib**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by wongni — APPROVED** [review]

**Review by wongni — APPROVED** [review]

**Review by jaxesn — APPROVED** [review]
/approve

**Comment by maxdrib** [comment]
Created https://github.com/aws/eks-anywhere-build-tooling/pull/827/files to cherry-pick into release branch

**Pull request merged**
