### PR TITLE
Use consistent sorting between macOS/Linux

### PR DESCRIPTION
**Pull request by ewollesen**
I also took the opportunity to apply some fixes suggested by
shellcheck, as well as some minor indentation adjustments for
consistency.

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by vincentni — APPROVED** [review]
/lgtm

**Comment by TerryHowe** [comment]
Is that the same presubmit that was failing earlier?

**Comment by ewollesen** [comment]
> Is that the same presubmit that was failing earlier?

I dunno. I guess I didn't know there was one failing earlier.

**Comment by jaxesn** [comment]
Yeah it's broken. Greg gave some instructions in the other pr for fixing it, but we need to get that fix in main. I'll ping him Monday to get that fixed, for now you can override it to ignore it

**Pull request merged**
