### PR TITLE
Updating tinkerbell project GIT_TAG files to releases

### PR DESCRIPTION
**Pull request by pokearu**
*Description of changes:*
Tinkerbell projects now have release tags 😄  Updating GIT_TAG files.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jaxesn** [comment]
Want to update the readme?  Its a small thing but...

https://github.com/aws/eks-anywhere-build-tooling/blob/af89071c9ec9ad29ef50624c78edad71cc027d11/projects/tinkerbell/hegel/README.md?plain=1#L2

**Comment by pokearu** [comment]
> Want to update the readme? Its a small thing but...
> 
> https://github.com/aws/eks-anywhere-build-tooling/blob/af89071c9ec9ad29ef50624c78edad71cc027d11/projects/tinkerbell/hegel/README.md?plain=1#L2

Yes sure! There is an issue with tink's release tag so I will update both readme along with that 👍
/hold

**Review by abhay-krishna — APPROVED** [review]
/lgtm

**Pull request merged**
