### PR TITLE
Create helm chart repos

### PR DESCRIPTION
**Pull request by ewollesen**
The create-ecr-repos Makefile target is extended to create the repos
of helm charts as well. In many cases the helm chart will end up in
one of the repos that's already created for a container image, but in
other cases, they're different repos, and this code will handle that
situation.

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by jaxesn — APPROVED** [review]
I like this!

**Comment by TerryHowe** [comment]
failing test looks like

**Comment by gwesterfieldjr** [comment]
https://github.com/aws/eks-anywhere-build-tooling/pull/788/commits/253fd6f3a11a5d5ceed4d371222bf3b86b5381ed

Apply these changes to fix presubmit. Looks like packer validate does not like default of null values.

**Pull request merged**
