### PR TITLE
image-builder: update checksum for Bottlerocket's new root.json

### PR DESCRIPTION
**Pull request by etungsten**
*Issue #, if available:*
N/A

*Description of changes:*
This updates the checksum for the newly deployed root.json that's used for accessing Bottlerocket's TUF repositories.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by mitalipaygude — APPROVED** [review]

**Review by vignesh-goutham — APPROVED** [review]
/ok-to-test
/approve
/cherrypick release-0.11

**Pull request merged**
