### PR TITLE
Remove individual project buildspecs

### PR DESCRIPTION
**Pull request by abhay-krishna**
These buildspecs are identical so removing them and instead just using the common one defined in #472.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by TerryHowe — APPROVED** [review]
/lgtm

**Review by vignesh-goutham — APPROVED** [review]
/lgtm
/approve

Thank you so much for doing this!

**Comment by abhay-krishna** [comment]
/override cluster-api-provider-cloudstack-tooling-presubmit

Just removing buildspecs

**Pull request merged**
