### PR TITLE
Add package attribution

### PR DESCRIPTION
**Pull request by ivyostosh**
*Issue #, if available:* N/A

*Description of changes:* Add package attribution

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by TerryHowe — APPROVED** [review]
/lgtm

**Comment by TerryHowe** [comment]
we probably need something to copy this file onto the container image

**Comment by ivyostosh** [comment]
> we probably need something to copy this file onto the container image

@TerryHowe Yes we had that taken care of already in a previous PR.

**Pull request merged**
