### PR TITLE
Update upgrader script to upgrade binaries only when there is a version diff 

### PR DESCRIPTION
**Pull request by rahulbabu95**
*Issue #, if available:*
Upgrader pod uses a upgrade.sh script that upgrades all the core kubernetes binaries with the binaries that are already baked into the pod. At present, we upgrade the binaries every time the script is invoked to upgrade a particular component. This change adds logic to the script to check if there is any version diff between the existing binary on the host and the binary baked into the pod before proceeding with the upgrade. 

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by jaxesn — COMMENTED** [review]
I wouldnt do it this way. Sometimes we rebuild due to new versions of go but that wont result in a new version. Instead we should use the shasum or some other approach. cc @g-gaston

**Comment by g-gaston** [comment]
yeah def use checksums and not versions

Now, do we need this now?
My main concern atomicity. Skipping the upgrade logic for kubeadm if the existing binary matches the new binary is dangerous, the two binaries being the same doesn't guarantee that the upgrade process succeed before. The container can be restarted mid process: after the binary has been copied but before the upgrade logic is run.

IMO the risk here is not worth the optimization benefits. We should write the upgrade logic in a way that is idempotent, so it can be run multiple times. If you want to be able to skip it, we need something smarter than just checking the version/checksum. We need to check the results of the actual upgrade, which involve knowing things about the kubeadm internals, etc. Or we use a "commit" strategy that records the success of each upgrade step for a particular upgrader version.

**Comment by rahulbabu95** [comment]
That's a very valid point. Yeah we need a mechanism to actually verify the upgrade had happened. We were looking to see if we could optimize the upgrade logic but looks like it's more involved than what it appeared to me in the first glance. I will hold this PR for now and discuss on how and if we want to do this at all.

**Pull request closed without merging**
