### PR TITLE
Standardize namespace setting and add missing on webhook

### PR DESCRIPTION
**Pull request by lewisdiamond**
*Description of changes:*
Standardize namespace setting across the chart (with default to what's in the values.yaml file).
Add missing namespacing to webhook service.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by TerryHowe — APPROVED** [review]
/lgtm

**Comment by TerryHowe** [comment]
all that approval and probably will fail checksums

**Comment by junshun** [comment]
This patches charts not images so no checksum fails I would think

**Pull request merged**
