### PR TITLE
Updated EKS-D to latest for all versions

### PR DESCRIPTION
**Pull request by kschumy**
*Description of changes:*
* Base image updates for all versions and etcd updates for 1.20 and 1.21
* This will likely be the last or second to last 1.20 release

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by kschumy** [comment]
/hold

versions are wrong

**Comment by kschumy** [comment]
/hold

waiting for the dang bot to update checksums itself

**Comment by kschumy** [comment]
Removed commit changing checksums
/unhold

**Comment by kschumy** [comment]
/unhold
literally the most dramatic EKS-D update ever

**Review by abhay-krishna — APPROVED** [review]
/approve

**Pull request merged**
