### PR TITLE
Update CAPT and Tink stack components to latest release for consuming L3 provisioning changes

### PR DESCRIPTION
**Pull request by rahulbabu95**
*Issue #, if available:*
https://github.com/aws/eks-anywhere-internal/issues/2792

*Description of changes:*
This PR bumps CAPT and multiple Tink Services to the latest release. 
Below are the list of version bumps:

- CAPT to [v0.6.1](https://github.com/tinkerbell/cluster-api-provider-tinkerbell/compare/v0.5.3...v0.6.1)
  - Remove [patch](https://github.com/aws/eks-anywhere-build-tooling/blob/main/projects/tinkerbell/cluster-api-provider-tinkerbell/patches/0001-Allow-inUse-and-provisioned-to-be-used-to-check-hard%20copy.patch) as the bootiing will be done through workflows and InUse label is directly attached to the hardware object once the workflow is complete from this [change](https://github.com/tinkerbell/cluster-api-provider-tinkerbell/pull/405) onwards
- Smee to  [v0.15.1](https://github.com/tinkerbell/smee/compare/v0.11.0...v0.15.1)
- Charts to [v0.6.2](https://github.com/tinkerbell/charts/compare/v0.4.5...v0.6.2)
  - Remove [patch](https://github.com/aws/eks-anywhere-build-tooling/blob/main/projects/tinkerbell/charts/helm/patches/0002-Use-smee-default-values-for-flags-when-running-in-ho.patch) to use smee default values for flags as in the bootstrap cluster, we do not use smee that's part of the chart deployment, but rather deploy smee as a docker container. Also, for the management cluster deployment once this we integrated [DHCP relay](https://github.com/aws/eks-anywhere/pull/8568), we access every tink service using the LB IP and not from the host IP. 
  - Additionally, there's an upstream [fix](https://github.com/tinkerbell/charts/pull/150) so that there's no defaulting needed anymore and is honored as is if the env vars are not set in the deployment.
- Rufio to [v0.6.1](https://github.com/tinkerbell/rufio/compare/v0.5.2...v0.6.1)
- Tinkerbell CRDS for [Rufio](https://github.com/tinkerbell/charts/tree/main/tinkerbell/rufio/crds) and [Tink](https://github.com/tinkerbell/charts/tree/main/tinkerbell/tink/crds)
  - This project is just used to install the CRDs and do not need the `values.yaml` as nothing gets templated here. Modify `helm_replace.sh` script to run the search and replace on values.yaml file only if present to handle cases like this where a values.yaml might not be required.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by rahulbabu95** [comment]
/test linuxkit-tooling-presubmit-amd64 kustomize-controller-tooling-presubmit 
kube-vip-tooling-presubmit kube-rbac-proxy-tooling-presubmit kind-1-31-tooling-presubmit kind-1-30-tooling-presubmit kind-1-29-tooling-presubmit kind-1-28-tooling-presubmit kind-1-27-tooling-presubmit hub-tooling-presubmit hook-tooling-presubmit-amd64 helm-tooling-presubmit

**Comment by rahulbabu95** [comment]
/test eks-a-admin-image-presubmit cluster-api-provider-vsphere-tooling-presubmit cluster-api-provider-tinkerbell-tooling-presubmit cluster-api-provider-nutanix-tooling-presubmit cluster-api-provider-cloudstack-tooling-presubmit cluster-api-provider-aws-snow-tooling-presubmit cloudstack-cloudmonkey-tooling-presubmit cloud-provider-vsphere-1-31-tooling-presubmit cloud-provider-vsphere-1-30-tooling-presubmit cloud-provider-vsphere-1-29-tooling-presubmit cloud-provider-vsphere-1-28-tooling-presubmit cloud-provider-vsphere-1-27-tooling-presubmit cloud-provider-nutanix-tooling-presubmit cloud-provider-aws-1-31-tooling-presubmit cloud-provider-aws-1-30-tooling-presubmit cloud-provider-aws-1-29-tooling-presubmit cloud-provider-aws-1-28-tooling-presubmit

**Review by jacobweinstock — APPROVED** [review]

**Review by jacobweinstock — CHANGES_REQUESTED** [review]
The CRDs need to have some CAPI annotations i believe. They also previously had some helm annotations that are removed in this. I suggest checking with @ahreehong on this.

**Review by jacobweinstock — APPROVED** [review]

**Pull request merged**
