### PR TITLE
Add target to upload source controller artifacts

### PR DESCRIPTION
**Pull request by abhay-krishna**
Adding this target so `POST_BUILD` phase doesn't complain.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by abhay-krishna** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/aws/eks-anywhere-build-tooling/pull/165#" title="Author self-approved">abhay-krishna</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=aws%2Feks-anywhere-build-tooling).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/aws/eks-anywhere-build-tooling/blob/main/OWNERS)~~ [abhay-krishna]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by pokearu — APPROVED** [review]
/lgtm

**Comment by abhay-krishna** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/aws/eks-anywhere-build-tooling/pull/165#" title="Author self-approved">abhay-krishna</a>*, *<a href="https://github.com/aws/eks-anywhere-build-tooling/pull/165#pullrequestreview-804353153" title="LGTM">pokearu</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=aws%2Feks-anywhere-build-tooling).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/aws/eks-anywhere-build-tooling/blob/main/OWNERS)~~ [abhay-krishna,pokearu]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by jaxesn — APPROVED** [review]
/lgtm

I am eventually going to go thru and remove all these where we don't really need them. What do we have to change at that point to keep codebuild happy?

**Comment by abhay-krishna** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/aws/eks-anywhere-build-tooling/pull/165#" title="Author self-approved">abhay-krishna</a>*, *<a href="https://github.com/aws/eks-anywhere-build-tooling/pull/165#pullrequestreview-804353325" title="LGTM">jaxesn</a>*, *<a href="https://github.com/aws/eks-anywhere-build-tooling/pull/165#pullrequestreview-804353153" title="LGTM">pokearu</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=aws%2Feks-anywhere-build-tooling).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/aws/eks-anywhere-build-tooling/blob/main/OWNERS)~~ [abhay-krishna,jaxesn,pokearu]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by abhay-krishna** [comment]
> /lgtm
> 
> I am eventually going to go thru and remove all these where we don't really need them. What do we have to change at that point to keep codebuild happy?

Yeah I kinda put this PR only as a temporary fix. We can remove the post_build phase from the buildspecs for projects we don't need to upload. Then it wuld just run make release, upload images and that's it. For projects that do upload artifacts, we would need to retain the post_build where we run `make upload-artifacts` or change the release target to handle that.

**Pull request merged**
