### PR TITLE
Fix pipeline builds

### PR DESCRIPTION
**Pull request by TerryHowe**

### CODE REVIEW

**Review by jonahjon — APPROVED** [review]

**Comment by jonahjon** [comment]
Is the bot broke?

**Comment by ewollesen** [comment]
> Is the bot broke?

Interesting... One of the [presubmits failed to run](https://prow.eks.amazonaws.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-anywhere-build-tooling/613/harbor-tooling-presubmit/1508557246399778816), but prow says it passed anyway... Even though it clearly timedout.

Let's try this...

/retest

**Comment by ewollesen** [comment]
/test all

Trying this since prow thinks things passed that didn't.

**Pull request merged**
