### PR TITLE
Updated EKS-D to latest for all versions

### PR DESCRIPTION
**Pull request by kschumy**
*Issue #, if available:*
closes https://github.com/aws/eks-distro/issues/1464

*Description of changes:*
* Updated to EKS-D 1.21-21, 1.22-13, 1.23-8, 1.24-3

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by kschumy** [comment]
/hold

release is out and this can be unhold/merged whenever you want it

**Comment by jaxesn** [comment]
Leave hold please, I'll merge when ready. Testing some template importing

**Review by jaxesn — APPROVED** [review]
/approve
/unhold
/lgtm

**Pull request merged**
