### PR TITLE
Change helm charts to use semantic versioning

### PR DESCRIPTION
**Pull request by TerryHowe**

### CODE REVIEW

**Review by jonahjon — APPROVED** [review]

**Comment by ewollesen** [comment]
Have you tested this? When I tried it locally, it produced a filename without the `v` (because helm package appends the version to the filename), but the `helm_push.sh` script was still expecting the `v`, and so it failed. We might be able to do some shenanigans in `helm_push.sh` to make it work, but that seems like it would be cryptic.

**Comment by TerryHowe** [comment]
I just did a helm/build

**Comment by TerryHowe** [comment]
No idea if there is going to fix upgrade, but it does build and install

**Comment by ewollesen** [comment]
Heh, this is why you make the big bucks, Terry. <3

Would you need to update `helm_require.sh` as well? I'm looking at the metadata/name value in the requires file, and wondering if it shouldn't remove the `v` as well? I'll see if I can make a suggestion.

**Comment by TerryHowe** [comment]
/override harbor-tooling-presubmit
Harbor presubmit fails due to lack of disk space

**Review by jaxesn — APPROVED** [review]
/lgtm

**Pull request merged**
