### PR TITLE
Add json schema to requires.yaml file

### PR DESCRIPTION
**Pull request by a-cool-train**
*Description of changes:*
Add gzipped, base64 encoded json schema to requires.yaml file.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by TerryHowe — APPROVED** [review]
/hold
/lgtm

I put the hold on in case the generate bundle blows up not recognizing "schema" or requires the old "config"

**Review by jonahjon — CHANGES_REQUESTED** [review]
We need to keep the requires.yaml, otherwise all the promotion/release stuff will break. I think we could just add the shema.json as an additional file into the helm chart.

**Comment by TerryHowe** [comment]
> We need to keep the requires.yaml, otherwise all the promotion/release stuff will break. I think we could just add the shema.json as an additional file into the helm chart.


Okay, this change just adds the schema to the requires.yaml. We need the requires.yaml because it contains the image list anyway

```
---
kind: EksaPackageRequires
metadata:
  name: hello-eks-anywhere-0.1.1-9c8ee6988061bd7b0ced2f89ef7b1c21bcecf6fa
  namespace: eksa-packages
spec:
  images:
  - repository: hello-eks-anywhere
    tag: v0.1.1-9c8ee6988061bd7b0ced2f89ef7b1c21bcecf6fa
    digest: sha256:d4ad935f6b54763d346760e987e82cce2228797f1c179d76f2f223d0141381bf
    schema: H4sIAAAAAAAAA51Ry27CMBC85yusqMfGoRy5oaqnXir4gsXZJAbHttYboRTx7zWOQagc+rjO7LzsUyFE+aSbciXKntmHVV33aIyr8BAqsNOxR0LpQR2gwyAjKmGAT2fhGKRyQx1UjwPIfXC2fE5uM3LveCGrfOioqxuCluvlYrmoXpbZYRazZoNJ+lAiH0w+8W63R8Uz5sl5JNYYInOKSMSCG0nhBjsdmKYbfucQcW275JDwBlsYDV8oP+6MVhIVyTizfmiR74Mi7VnH4VGzTYGCcqJoHYn8bLJMmvMsvW38S6N1enPx9r4V65+avDrLoC2SSEnf0sO4+0+BzTinayumuFQ0wKDQMtIvelwzr1WKXKeEptGXczAf93/YgglYnIsv0Gdet54CAAA=
```

**Review by jonahjon — APPROVED** [review]

**Review by TerryHowe — APPROVED** [review]
/lgtm

**Pull request merged**
