### PR TITLE
Update Nutanix CAPX Provider to v1.1.3

### PR DESCRIPTION
**Pull request by thunderboltsid**
The new version ensures VMs are given the same name as the CAPI machines. Earlier, VMs were being named on NutanixMachine names.

### CODE REVIEW

**Comment by thunderboltsid** [comment]
Hmm, running `make update-attribution-checksum-docker` seems to be giving an error.
```
$ make update-attribution-checksums-docker
/Users/sid.shukla/go/src/github.com/nutanix-cloud-native/aws-eks-anywhere-build-tooling/build/lib/update_checksum_docker.sh nutanix-cloud-native/cluster-api-provider-nutanix 770301640873.dkr.ecr.us-west-2.amazonaws.com
/Users/sid.shukla/go/src/github.com/nutanix-cloud-native/aws-eks-anywhere-build-tooling/build/lib/run_target_docker.sh: line 24: ARTIFACTS_BUCKET: unbound variable
make: *** [update-attribution-checksums-docker] Error 1
```

**Comment by thunderboltsid** [comment]
> Hmm, running `make update-attribution-checksum-docker` seems to be giving an error.
> 
> ```
> $ make update-attribution-checksums-docker
> /Users/sid.shukla/go/src/github.com/nutanix-cloud-native/aws-eks-anywhere-build-tooling/build/lib/update_checksum_docker.sh nutanix-cloud-native/cluster-api-provider-nutanix 770301640873.dkr.ecr.us-west-2.amazonaws.com
> /Users/sid.shukla/go/src/github.com/nutanix-cloud-native/aws-eks-anywhere-build-tooling/build/lib/run_target_docker.sh: line 24: ARTIFACTS_BUCKET: unbound variable
> make: *** [update-attribution-checksums-docker] Error 1
> ```

Temporarily getting rid of the unbound variable did the trick.

**Review by TerryHowe — COMMENTED** [review]
/ok-to-test

**Comment by thunderboltsid** [comment]
Swapped out the hashes to the one from the job but do we know why generating the checksums locally fails?

**Review by abhinavmpandey08 — COMMENTED** [review]
Is there anything else major that changed between v1.1.1 and v1.1.3 besides the VM name changes?

**Comment by thunderboltsid** [comment]
> Is there anything else major that changed between v1.1.1 and v1.1.3 besides the VM name changes?

Here are some other changes that have happened in the meanwhile although nothing major.
- Default max-concurrent-reconciles set to 10
- Support for deploying clusters on Overlay networks (spanning multiple PEs)
- KubeVIP version update

**Review by abhinavmpandey08 — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
