### PR TITLE
Tag artifacts based on branch they are built from

### PR DESCRIPTION
**Pull request by abhay-krishna**
In cases where we want to build from an older release branch and not main, we should not tag the images as `latest` and instead use the branch name as the identifier. Same applies to the destination folder we use for the S3 artifacts.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by abhay-krishna** [comment]
@abhay-krishna: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
kind-tooling-presubmit | 344a9cf3418f7f902357cc58540726b060719bf4 | [link](https://prow.eks.amazonaws.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-anywhere-build-tooling/69/kind-tooling-presubmit/1445588030634070016) | `/test kind-tooling-presubmit`

[Full PR test history](https://prow.eks.amazonaws.com/pr-history?org=aws&repo=eks-anywhere-build-tooling&pr=69). [Your PR dashboard](https://prow.eks.amazonaws.com/pr?query=is:pr+state:open+author:abhay-krishna).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Review by TerryHowe — APPROVED** [review]
/lgtm

**Review by jaxesn — APPROVED** [review]
/lgtm

**Comment by abhay-krishna** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/aws/eks-anywhere-build-tooling/pull/69#" title="Author self-approved">abhay-krishna</a>*, *<a href="https://github.com/aws/eks-anywhere-build-tooling/pull/69#pullrequestreview-795846920" title="LGTM">jaxesn</a>*, *<a href="https://github.com/aws/eks-anywhere-build-tooling/pull/69#pullrequestreview-772512781" title="LGTM">TerryHowe</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=aws%2Feks-anywhere-build-tooling).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/aws/eks-anywhere-build-tooling/blob/main/OWNERS)~~ [TerryHowe,abhay-krishna,jaxesn]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by abhay-krishna** [comment]
@abhay-krishna: you cannot LGTM your own PR.

<details>

In response to [this](https://github.com/aws/eks-anywhere-build-tooling/pull/69#issuecomment-958133137):

>/lgtm


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Comment by abhay-krishna** [comment]
@abhay-krishna: [dog image](https://storage.googleapis.com/this-is-fine-images/this_is_not_fine.png)

<details>

In response to [this](https://github.com/aws/eks-anywhere-build-tooling/pull/69#issuecomment-958133762):

>/this-is-not-fine


Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
</details>

**Pull request merged**
