### PR TITLE
Add Instructions for Validating Helm Chart

### PR DESCRIPTION
**Pull request by jonathanmeier5**
*Description of changes:*
Add some documentation to reduce friction in the process of developing and testing curated packages helm charts.

Note that this does not test the helm chart's schema, as that would require generating a bundle and installing
in a cluster running the package controller.

However, this does verify that the helm chart itself is valid yaml and install as expected.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by jaxesn — COMMENTED** [review]
This is a great start! Can you make sure other packages sme's do something similar for theirs?

**Comment by jonathanmeier5** [comment]
> This is a great start! Can you make sure other packages sme's do something similar for theirs?

will do 👍

**Pull request merged**
