### PR TITLE
Adds slash hold to add label instead of API labels arg

### PR DESCRIPTION
**Pull request by markapruett**
*Issue #, if available:*

*Description of changes:*
Same change that was done in https://github.com/aws/eks-distro-build-tooling/pull/757

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by TerryHowe — APPROVED** [review]
/lgtm

**Comment by markapruett** [comment]
This isn't working in eks-d. Holding until I fix it

**Review by jaxesn — APPROVED** [review]

**Pull request merged**
