### PR TITLE
Make image names same as production

### PR DESCRIPTION
**Pull request by TerryHowe**

### CODE REVIEW

**Comment by abhay-krishna** [comment]
@TerryHowe: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
eks-anywhere-diagnostic-collector-tooling-presubmit | 4f2a433c51dd49519b4026326f7f9a1d53335ce5 | [link](https://prow.eks.amazonaws.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-anywhere-build-tooling/45/eks-anywhere-diagnostic-collector-tooling-presubmit/1443292335373815808) | `/test eks-anywhere-diagnostic-collector-tooling-presubmit`

[Full PR test history](https://prow.eks.amazonaws.com/pr-history?org=aws&repo=eks-anywhere-build-tooling&pr=45). [Your PR dashboard](https://prow.eks.amazonaws.com/pr?query=is:pr+state:open+author:TerryHowe).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by abhay-krishna** [comment]
@TerryHowe: The following test **failed**, say `/retest` to rerun all failed tests:

Test name | Commit | Details | Rerun command
--- | --- | --- | ---
eks-anywhere-diagnostic-collector-tooling-presubmit | 4f2a433c51dd49519b4026326f7f9a1d53335ce5 | [link](https://prow.eks.amazonaws.com/view/s3/prowpresubmitsdataclusterstack-prowbucket7c73355c-vfwwxd2eb4gp/pr-logs/pull/aws_eks-anywhere-build-tooling/45/eks-anywhere-diagnostic-collector-tooling-presubmit/1447904204612964352) | `/test eks-anywhere-diagnostic-collector-tooling-presubmit`

[Full PR test history](https://prow.eks.amazonaws.com/pr-history?org=aws&repo=eks-anywhere-build-tooling&pr=45). [Your PR dashboard](https://prow.eks.amazonaws.com/pr?query=is:pr+state:open+author:TerryHowe).

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>

**Comment by abhay-krishna** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/aws/eks-anywhere-build-tooling/pull/45#" title="Author self-approved">TerryHowe</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=aws%2Feks-anywhere-build-tooling).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/aws/eks-anywhere-build-tooling/blob/main/OWNERS)~~ [TerryHowe]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by jaxesn** [comment]
I dont think we want to do this one. In prod the registry is eks-anywhere so it doesn't make sense to have that in the name, but in staging/build its a random name so having the eks-anywhere prefix is more clear.

This would also require changing the ecr repos, which im not sure we want to do?  Adding a hold and tagging @abhay-krishna to decide if this is something we should merge or close.

/hold

**Pull request closed without merging**
