### PR TITLE
checksum fix for codepipeline

### PR DESCRIPTION
**Pull request by jonahjon**
Signed-off-by: jonahjon <jonahjones094@gmail.com>

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by TerryHowe** [comment]
update from prow?

**Comment by TerryHowe** [comment]
there is supposed to be a bot that generates these checksums. Is emissary not on that list?

**Comment by jonahjon** [comment]
> there is supposed to be a bot that generates these checksums. Is emissary not on that list?

The issue is the checksums from prow are failing in codepipeline

**Comment by jonahjon** [comment]
> there is supposed to be a bot that generates these checksums. Is emissary not on that list?

This was the error message on codepipeline.

```

Please only update if changing GIT_TAG or build flags.
--
721 | *************** CHECKSUMS ***************
722 | 42c3a8a2c089fdf6cd71dd2453673186c40bf3f2da9a92f5aac6f61cb2ca130e  _output/bin/emissary/linux-amd64/busyambassador
723 | 97f6df78e8d72248090f8338d162f2eb0b7f702e9a9d3ec24c6e6e24b752b365  _output/bin/emissary/linux-amd64/capabilities_wrapper
724 | 4bea28fc4647d2308f21ea3c219944dd6f8001a67b396bbbd8a6358387221b5b  _output/bin/emissary/linux-amd64/example-envoy-metrics-sink
725 | 317df21fce22c79e211de944450fa6b40ce4775b6a34c0bc1f69e40c645fb8ab  _output/bin/emissary/linux-amd64/k8sregistryctl
726 | 449eedbd4b88c67a88b4489d834dd067bbd6f8ed368f6b4edcbe76a288d4335d  _output/bin/emissary/linux-amd64/kat-client
727 | 7b931be2f94488d41c156f514ea283a1fe0d6df5bceee8f6846337279061bc90  _output/bin/emissary/linux-amd64/kat-server
728 | 03a57c2880f3553b066c25759628226e58bd6592d10a03e1130027a103785357  _output/bin/emissary/linux-arm64/busyambassador
729 | 2344d1183ab5617fb3a3ae3fd585c0581186393e8ee2997e922e8b4881597fdb  _output/bin/emissary/linux-arm64/capabilities_wrapper
730 | 6cd5f8050ebc2a00ee2842b3c11ff433b3363ff46b379a032f5926cbc2eee6ce  _output/bin/emissary/linux-arm64/example-envoy-metrics-sink
731 | e187225dd1a47ce50abdf3d4473181acc0117ebf2914d11c2817edf7deb0cadd  _output/bin/emissary/linux-arm64/k8sregistryctl
732 | 861a8c6b13163870f0e51feabe49db929bb10f642e9e776825abed04f1988187  _output/bin/emissary/linux-arm64/kat-client
733 | 2264c9b233e13c450f60653d1d4e73a3440e6b0a5d0f8404ac019a2f4e7d745a  _output/bin/emissary/linux-arm64/kat-server
734 | *****************************************

````

**Comment by TerryHowe** [comment]
Could it be the codepipeline doesn't have the correct go version?

**Pull request closed without merging**
