### PR TITLE
Updated EKS-D versions

### PR DESCRIPTION
**Pull request by kschumy**
*Issue #, if available:*

*Description of changes:*
* Bumped all EKS-D versions for all releases
* Changed 1.22 Kubernetes version from 1.22.4 to 1.22.6

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by kschumy** [comment]
/hold

This is good to go. Unhold whenever you're ready to merge it

**Review by TerryHowe — APPROVED** [review]
/lgtm

**Review by jaxesn — APPROVED** [review]
/lgtm
/unhold

**Pull request merged**
